// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjJvOBQM166raBCbvX8_AvwnXivaTdQ_g',
    appId: '1:43077897549:web:ddd49c1d9aa11733577b04',
    messagingSenderId: '43077897549',
    projectId: 'chatappjordan-fefcd',
    authDomain: 'chatappjordan-fefcd.firebaseapp.com',
    storageBucket: 'chatappjordan-fefcd.firebasestorage.app',
    measurementId: 'G-0SKB2NJ8GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAS5DbMaxExivwVtZDtwUKsIS2orh_Jns',
    appId: '1:43077897549:android:acb61e6fd51fbe04577b04',
    messagingSenderId: '43077897549',
    projectId: 'chatappjordan-fefcd',
    storageBucket: 'chatappjordan-fefcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH-G21n9P7NgiHwvrl5D8atNWfiILgTKI',
    appId: '1:43077897549:ios:894326f5b5f2757c577b04',
    messagingSenderId: '43077897549',
    projectId: 'chatappjordan-fefcd',
    storageBucket: 'chatappjordan-fefcd.firebasestorage.app',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH-G21n9P7NgiHwvrl5D8atNWfiILgTKI',
    appId: '1:43077897549:ios:894326f5b5f2757c577b04',
    messagingSenderId: '43077897549',
    projectId: 'chatappjordan-fefcd',
    storageBucket: 'chatappjordan-fefcd.firebasestorage.app',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjJvOBQM166raBCbvX8_AvwnXivaTdQ_g',
    appId: '1:43077897549:web:ca828e72368dffb6577b04',
    messagingSenderId: '43077897549',
    projectId: 'chatappjordan-fefcd',
    authDomain: 'chatappjordan-fefcd.firebaseapp.com',
    storageBucket: 'chatappjordan-fefcd.firebasestorage.app',
    measurementId: 'G-RV0XVT6X3E',
  );
}
